import express from 'express';
    import serverless from 'serverless-http';
    // ... your routes and middleware ...
    const app = express();
    // ... your routes and middleware ...
    export default serverless(app);